### ISSUE TITLE
Crypto-crack code

### ISSUE THREAD

**Issue by agjunyent** [decurtoydiaz/learning_with_signatures#2]
I tried your code with random-generated input and labels data and still giving 100% accuracy

Did you just break and solve randomness in computer science? Is sha cracked?

**Comment by decurtoydiaz** [comment]
Thanks for the comment. Here scale factors are computed optimally assuming you can resolve at test time the ambiguity, using for example the same criteria used to derive the weights (which is not explained in the code). De Curtò y DíAz.

**Comment by agjunyent** [comment]
How can you resolve the ambiguity of randomness?

If I change all labels of the Cifar10 to the same number, will your method converge and learn too?

I'd go for a Nobel price if that's the case. You have the perfect mathematical model to predict anything you want

**Comment by decurtoydiaz** [comment]
If you play a bit and change the parameters you'll see that the method doesn't get always 100%. Those sequences are probably pseudorandom numbers and not so difficult to classify. And again here scale factors are computed optimally assuming you can resolve at test time the ambiguity, using for example the same criteria used to derive the weights (which is not explained in the code). 

This means that there is an optimal scale factor that gives 100% accuracy. So that if you can resolve the ambiguity at test time you can achieve it.

De Curtò y DíAz.

**Comment by agjunyent** [comment]
You only have 1 paragraph to repeat in all your responses. All other words are blank and without any meaning.

The fact that you provide 0 real prove with an information-leaking implementation says everything we need to know.

Thanks for your time and the amazing laugh I'm having

**Comment by mimocha** [comment]
> Those sequences are probably pseudorandom numbers and not so difficult to classify

Tp put it very lightly, that is some _strong_ claim to be making. The default Python library uses the Mersenne Twister [[1]](https://docs.python.org/3/library/random.html), while default Numpy uses PCG64 [[2]](https://numpy.org/doc/stable/reference/random/generator.html). While those are not cryptographic PRNGs, claiming you can some how "classify" two streams of random numbers (from two very well proven PRNGs) is just absolutely absurd.

Are you saying that this implementation of signature transform is capable of learning from the underlying PRNGs, predicting the next bit, and finding the correct mapping between multiple PRNG streams; all on a classical computer, in polynomial time?

Even ignoring the fact that I still don't believe _"there is an optimal scale factor that gives 100% accuacy"_, I still need the answer to how you even find that optimal scale factor within a reasonable runtime or memory to begin with.

**Comment by agjunyent** [comment]
You are even now removing comments...

> Tp put it very lightly, that is some strong claim to be making. The default Python library uses the Mersenne Twister [[1]](https://docs.python.org/3/library/random.html), while default Numpy uses PCG64 [[2]](https://numpy.org/doc/stable/reference/random/generator.html). While those are not cryptographic PRNGs, claiming you can some how "classify" two streams of random numbers (from two very well proven PRNGs) is just absolutely absurd.
> 
> Are you saying that this implementation of signature transform is capable of learning from the underlying PRNGs, predicting the next bit, and finding the correct mapping between multiple PRNG streams; all on a classical computer, in polynomial time?
> 
> Even ignoring the fact that I still don't believe "there is an optimal scale factor that gives 100% accuacy", I still need the answer to how you even find that optimal scale factor within a reasonable runtime or memory to begin with.

Everything you are claiming does not sustain in any of the parts, and all comments that try to prove you are wrong are deleted.

What a time to be alive

**Comment by decurtoydiaz** [comment]
Please stop sending comments outside the topic of discussion. Be considerate and respectful in your discourse. This is not about cryptography. 
Code is a generalization of our previous paper, you can take a look here https://github.com/decurtoydiaz/signatures
We are only showing that there exists a probably optimal lambda that gives very good generalization (and that can be computed analytically; which is astonishing). Those weights can be also chosen by grid search or other methods. The method is general and the paper is still not accepted. Will update the code consequently. De Curtò y DíAz.

**Comment by decurtoydiaz** [comment]
Please check the new updated code. The ambiguity in test is determined using one-vs-all fixing the proper lambda. You get n-classifiers one per class. Accuracy 100%.

De Curtò y DíAz.

--
https://www.decurto.tw/
